const $=s=>document.querySelector(s);let history=[];
async function load(){const status=await chrome.runtime.sendMessage({type:'get-status'});history=status.history||[];$('#enabled').checked=status.enabled;$('#state').textContent=status.enabled?'Watching':'Paused';$('#state').className=status.enabled?'':'off';const when=status.urlhausUpdated?new Date(status.urlhausUpdated).toLocaleString():'not downloaded yet';$('#feedStatus').textContent='Threat feed: '+status.feedCount.toLocaleString()+' hosts • updated '+when;render();chrome.runtime.sendMessage({type:'clear-badge'})}
function render(){const q=$('#search').value.toLowerCase(),f=$('#filter').value;let shown=history.filter(x=>((x.name||'')+' '+(x.reasons||[]).join(' ')).toLowerCase().includes(q));if(f==='risk')shown=shown.filter(x=>x.level!=='safe');if(f==='paused')shown=shown.filter(x=>x.paused);if(f==='safe')shown=shown.filter(x=>x.level==='safe');$('#total').textContent=history.length;$('#warn').textContent=history.filter(x=>x.level!=='safe').length;$('#blocked').textContent=history.filter(x=>x.paused).length;const list=$('#list');list.innerHTML='';if(!shown.length)list.innerHTML='<div class="item meta">No matching downloads.</div>';for(const x of shown){const el=document.createElement('div');el.className='item';el.innerHTML='<span class="tag"></span><div class="name"></div><div class="meta"></div><div class="actions"></div>';const tag=el.querySelector('.tag');tag.textContent=x.level;tag.className='tag '+x.level;el.querySelector('.name').textContent=x.name;let source='';try{source=new URL(x.url).hostname}catch{}el.querySelector('.meta').textContent=(source?source+' • ':'')+'Chrome: '+(x.chromeVerdict||'Unknown')+' • '+((x.reasons||[]).join(' • ')||'No basic warning signs')+' • '+new Date(x.createdAt).toLocaleString();const actions=el.querySelector('.actions');if(x.paused){const resume=document.createElement('button');resume.textContent='Resume anyway';resume.onclick=async()=>{if(confirm('Continue only if you trust the file and its source.')){await chrome.runtime.sendMessage({type:'resume',id:x.id});x.paused=false;await update()}};const cancel=document.createElement('button');cancel.textContent='Cancel download';cancel.onclick=async()=>{await chrome.runtime.sendMessage({type:'cancel',id:x.id});x.paused=false;x.level='blocked';x.reasons=[...(x.reasons||[]),'Download cancelled'];await update()};actions.append(resume,cancel)}list.append(el)}}
async function update(){await chrome.storage.local.set({history});render()}
$('#enabled').onchange=async e=>{await chrome.runtime.sendMessage({type:'set-enabled',enabled:e.target.checked});$('#state').textContent=e.target.checked?'Watching':'Paused';$('#state').className=e.target.checked?'':'off'};
$('#checkUrl').onclick=async()=>{const r=await chrome.runtime.sendMessage({type:'risk-url',url:$('#url').value});$('#urlResult').className='result '+r.level;$('#urlResult').textContent='Risk '+r.score+'/100 — '+(r.reasons.length?r.reasons.join(' • '):'No obvious warning signs')};
$('#search').oninput=render;$('#filter').onchange=render;
$('#clear').onclick=async()=>{if(confirm('Clear extension history?')){history=[];await update()}};
$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({product:'GitHub Protect Extension',version:'2.0.0',created:new Date().toISOString(),history},null,2)],{type:'application/json'}));a.download='github-protect-extension-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
$('#settings').onclick=()=>chrome.runtime.openOptionsPage();load();