(()=>{
const ID='G-5SW1S6NYZK',KEY='githubProtectAnalyticsConsent',PRIVACY='/github-protect/privacy/';
const $=s=>document.querySelector(s);
let loaded=false;
function loadAnalytics(){if(loaded)return;loaded=true;window.dataLayer=window.dataLayer||[];window.gtag=window.gtag||function(){dataLayer.push(arguments)};gtag('js',new Date());gtag('config',ID,{send_page_view:true,allow_google_signals:false,allow_ad_personalization_signals:false});const s=document.createElement('script');s.async=true;s.src='https://www.googletagmanager.com/gtag/js?id='+encodeURIComponent(ID);s.referrerPolicy='strict-origin-when-cross-origin';document.head.append(s)}
function style(){if($('#gp-consent-style'))return;const s=document.createElement('style');s.id='gp-consent-style';s.textContent=`.gp-consent{position:fixed;z-index:2147483000;left:50%;bottom:16px;transform:translateX(-50%);width:min(720px,calc(100vw - 24px));padding:1rem;background:#0b1225;color:#f7f9ff;border:1px solid #536797;border-radius:18px;box-shadow:0 20px 65px #000c;font:500 15px/1.5 system-ui,sans-serif}.gp-consent h2{font-size:1.05rem;margin:0 0 .35rem}.gp-consent p{margin:.25rem 0 .8rem;color:#cbd4eb}.gp-consent-actions{display:flex;gap:.55rem;flex-wrap:wrap}.gp-consent button,.gp-consent a{border:1px solid #7185bb;border-radius:10px;padding:.62rem .78rem;font:800 14px system-ui,sans-serif;cursor:pointer;text-decoration:none}.gp-consent .accept{background:#6f7cff;color:#fff;border-color:#6f7cff}.gp-consent .decline,.gp-consent a{background:#111b33;color:#fff}.gp-analytics-settings{position:fixed;z-index:10009;left:50%;bottom:4px;transform:translateX(-50%);border:1px solid #5a6f9f;border-radius:999px;background:#0b1225;color:#dfe6ff;padding:.32rem .62rem;font:700 11px system-ui,sans-serif;cursor:pointer;opacity:.82}.gp-consent-status{font-size:.75rem!important;color:#aeb9d3!important}@media(max-width:560px){.gp-consent{bottom:8px}.gp-consent-actions>*{flex:1;text-align:center}.gp-analytics-settings{bottom:2px}}`;document.head.append(s)}
function panel(settings=false){style();$('#gpConsent')?.remove();const choice=localStorage.getItem(KEY);const el=document.createElement('section');el.className='gp-consent';el.id='gpConsent';el.setAttribute('role','dialog');el.setAttribute('aria-label','Analytics privacy choice');el.innerHTML=`<h2>${settings?'Analytics settings':'Help improve GitHub Protector?'}</h2><p>With your permission, anonymous Google Analytics measures page views, traffic sources, country, device type and general engagement. It never receives filenames, file contents, pasted messages, passwords or Security AI questions.</p>${settings&&choice?`<p class="gp-consent-status">Current choice: <b>${choice==='accepted'?'Analytics allowed':'Analytics declined'}</b></p>`:''}<div class="gp-consent-actions"><button class="accept" id="gpAcceptAnalytics">Accept analytics</button><button class="decline" id="gpDeclineAnalytics">Continue without analytics</button><a href="${PRIVACY}">Privacy details</a></div>`;document.body.append(el);$('#gpAcceptAnalytics').onclick=()=>choose('accepted');$('#gpDeclineAnalytics').onclick=()=>choose('declined');$('#gpAcceptAnalytics').focus()}
function settingsButton(){if($('#gpAnalyticsSettings'))return;const b=document.createElement('button');b.id='gpAnalyticsSettings';b.className='gp-analytics-settings';b.textContent='Analytics settings';b.onclick=()=>panel(true);document.body.append(b)}
function choose(value){const previous=localStorage.getItem(KEY);localStorage.setItem(KEY,value);$('#gpConsent')?.remove();settingsButton();if(value==='accepted')loadAnalytics();else if(previous==='accepted'&&window.gtag){gtag('consent','update',{analytics_storage:'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});location.reload()}}
function init(){style();const choice=localStorage.getItem(KEY);if(choice==='accepted'){loadAnalytics();settingsButton()}else if(choice==='declined'){settingsButton()}else{panel(false)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
