(()=>{
'use strict';
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const STORAGE={routine:'githubProtectProRoutine',interest:'githubProtectProInterest'};

const style=document.createElement('style');
style.textContent=`
:root{--pro:#a78bfa;--pro2:#38bdf8;--proGold:#f8d477}
body:before{content:'';position:fixed;inset:0;z-index:-1;pointer-events:none;background:radial-gradient(circle at 50% 8%,rgba(124,92,255,.12),transparent 34%)}
.pro-top-chip{display:inline-flex;align-items:center;gap:7px;min-height:36px;padding:7px 11px;border:1px solid rgba(167,139,250,.48);border-radius:11px;background:linear-gradient(135deg,rgba(124,92,255,.2),rgba(56,189,248,.09));color:#e9e1ff;font-size:12px;font-weight:900;cursor:pointer}
.pro-workspace{position:relative;margin-top:20px;padding:0;overflow:hidden;border-color:rgba(167,139,250,.5);background:linear-gradient(145deg,rgba(26,21,55,.98),rgba(10,19,35,.99) 55%,rgba(8,31,44,.98));box-shadow:0 30px 90px rgba(0,0,0,.5),0 0 70px rgba(124,92,255,.08)}
.pro-workspace:before{content:'';position:absolute;width:360px;height:360px;right:-130px;top:-180px;border-radius:50%;background:radial-gradient(circle,rgba(56,189,248,.21),transparent 66%);pointer-events:none}
.pro-hero{position:relative;display:grid;grid-template-columns:1.25fr .75fr;gap:28px;padding:34px;border-bottom:1px solid rgba(167,139,250,.22)}
.pro-label{display:inline-flex;align-items:center;gap:8px;padding:6px 10px;border:1px solid rgba(248,212,119,.42);border-radius:999px;background:rgba(248,212,119,.09);color:#ffe7a1;font-size:11px;font-weight:950;letter-spacing:.1em;text-transform:uppercase}
.pro-title{max-width:720px;margin:14px 0 11px;font-size:clamp(30px,4.8vw,54px);line-height:1;letter-spacing:-.045em}.pro-title span{background:linear-gradient(90deg,#fff,#c4b5fd 45%,#67e8f9);-webkit-background-clip:text;background-clip:text;color:transparent}
.pro-copy{max-width:720px;margin:0;font-size:16px}.pro-actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:21px}
.btn.pro-primary{background:linear-gradient(135deg,#a78bfa,#38bdf8);color:#07111e;box-shadow:0 12px 30px rgba(89,126,255,.3)}
.pro-score{align-self:center;padding:22px;border:1px solid rgba(103,232,249,.22);border-radius:19px;background:linear-gradient(160deg,rgba(18,39,63,.9),rgba(9,15,29,.85));box-shadow:inset 0 1px rgba(255,255,255,.05)}
.pro-score-ring{display:grid;place-items:center;width:112px;height:112px;margin:0 auto 15px;border-radius:50%;background:radial-gradient(circle at center,#0e1930 58%,transparent 60%),conic-gradient(#38d996 0 82%,#253752 82% 100%);font-size:30px;font-weight:950}.pro-score b{display:block;text-align:center;font-size:17px}.pro-score small{display:block;text-align:center;color:var(--muted)}
.pro-dashboard{padding:25px 30px 30px}.pro-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:11px}.pro-metric{padding:16px;border:1px solid #2d3f61;border-radius:15px;background:rgba(6,13,25,.72)}.pro-metric span{display:block;color:var(--muted);font-size:12px;font-weight:800}.pro-metric b{display:block;margin-top:4px;font-size:24px;letter-spacing:-.03em}
.pro-productivity{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.pro-panel{min-height:200px;padding:20px;border:1px solid #2d3f61;border-radius:17px;background:rgba(6,13,25,.72)}.pro-panel h3{margin:0 0 5px;font-size:18px}.pro-panel p{margin:0 0 15px}.pro-quick-grid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.pro-quick{padding:13px;border:1px solid #344a6b;border-radius:12px;background:#111e32;color:#e9f3ff;text-align:left;font-weight:850;cursor:pointer;transition:.15s}.pro-quick:hover{border-color:var(--pro2);transform:translateY(-1px)}
.pro-timeline{display:grid;gap:9px}.pro-event{display:grid;grid-template-columns:auto 1fr;gap:11px;align-items:start;padding:10px;border:1px solid #293b58;border-radius:11px;background:#091321}.pro-event-dot{width:10px;height:10px;margin-top:6px;border-radius:50%;background:var(--green);box-shadow:0 0 13px rgba(56,217,150,.55)}.pro-event strong,.pro-event small{display:block}.pro-event small{color:var(--muted)}
.plans{margin-top:22px;padding:30px;border-color:#334864;background:linear-gradient(160deg,#101a2c,#090f1a)}.plans-head{display:flex;justify-content:space-between;align-items:end;gap:18px;margin-bottom:19px}.plans-head h2{font-size:clamp(26px,4vw,40px);letter-spacing:-.04em}.plans-head p{max-width:640px;margin:7px 0 0}.plan-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.plan{position:relative;display:flex;flex-direction:column;min-height:420px;padding:23px;border:1px solid #30435f;border-radius:19px;background:#0a1220}.plan.featured{border-color:rgba(167,139,250,.72);background:linear-gradient(155deg,rgba(54,35,103,.66),#0b1728 58%);box-shadow:0 20px 55px rgba(38,24,74,.55);transform:translateY(-6px)}.plan-badge{position:absolute;right:16px;top:16px;padding:5px 9px;border-radius:999px;background:linear-gradient(135deg,#a78bfa,#38bdf8);color:#07111e;font-size:10px;font-weight:950;text-transform:uppercase}.plan h3{margin:0;font-size:22px}.plan-price{margin:15px 0 2px;font-size:29px;font-weight:950;letter-spacing:-.04em}.plan-price small{font-size:12px;color:var(--muted);letter-spacing:0}.plan ul{display:grid;gap:10px;margin:18px 0 24px;padding:0;list-style:none}.plan li{position:relative;padding-left:24px;color:#c9d8eb}.plan li:before{content:'✓';position:absolute;left:0;color:var(--green);font-weight:950}.plan .btn{width:100%;margin-top:auto}.plan-note{margin-top:10px;color:var(--muted);font-size:11px;text-align:center}
.pro-modal-grid{display:grid;gap:12px;margin:18px 0}.pro-field label{display:block;margin-bottom:6px;color:#c6d7eb;font-weight:800}.pro-field input,.pro-field select{width:100%;padding:12px;border:1px solid #38506f;border-radius:11px;background:#07101d;color:var(--txt)}.pro-modal-note{padding:12px;border-left:3px solid var(--pro);border-radius:9px;background:rgba(167,139,250,.09);color:#d9d1ec}.pro-success{color:var(--green);font-weight:900}
@media(max-width:860px){.pro-hero,.pro-productivity{grid-template-columns:1fr}.pro-score{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:16px}.pro-score-ring{margin:0}.pro-score b,.pro-score small{text-align:left}.pro-metrics{grid-template-columns:1fr 1fr}.plan-grid{grid-template-columns:1fr}.plan.featured{transform:none}}
@media(max-width:540px){.pro-hero,.pro-dashboard,.plans{padding:20px 15px}.pro-metrics{grid-template-columns:1fr 1fr}.pro-quick-grid{grid-template-columns:1fr}.plans-head{display:block}.pro-score{display:block}.pro-score-ring{margin:0 auto 15px}.pro-score b,.pro-score small{text-align:center}}
`;
document.head.append(style);

function readScans(){try{return JSON.parse(localStorage.getItem('githubProtectLastScan')||'[]')}catch{return[]}}
function riskStats(){const scans=readScans();return{total:scans.length,safe:scans.filter(x=>x.level==='safe').length,review:scans.filter(x=>x.level==='warn').length,risky:scans.filter(x=>x.level==='danger').length}}
function routine(){try{return JSON.parse(localStorage.getItem(STORAGE.routine)||'null')}catch{return null}}
function addAlert(title,reason){window.postMessage({source:'github-protect-extension',type:'security-alert',entry:{id:'pro-'+Date.now(),name:title,level:'warning',createdAt:Date.now(),reasons:[reason]}},location.origin)}
function downloadReport(){
 const scans=readScans(),stats=riskStats(),payload={product:'GitHub Protect Pro Preview',createdAt:new Date().toISOString(),summary:stats,files:scans.map(({name,size,level,label,reasons})=>({name,size,level,label,reasons}))};
 const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='github-protect-security-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function openModal(id){$('#'+id)?.classList.add('open')}
function closeModal(id){$('#'+id)?.classList.remove('open')}
function mountNav(){
 const nav=$('.nav-links');if(!nav||$('[data-target="#proWorkspace"]',nav))return;
 const button=document.createElement('button');button.className='nav-chip';button.dataset.target='#proWorkspace';button.textContent='★ Pro';button.onclick=()=>{$$('.nav-chip',nav).forEach(x=>x.classList.remove('active'));button.classList.add('active');$('#proWorkspace')?.scrollIntoView({behavior:'smooth',block:'start'})};nav.append(button);
}
function mountHeader(){
 const buttons=$('header .buttons');if(!buttons||$('#proTopChip'))return;
 const button=document.createElement('button');button.id='proTopChip';button.type='button';button.className='pro-top-chip';button.innerHTML='<span aria-hidden="true">✦</span> Pro preview';button.onclick=()=>$('#proWorkspace')?.scrollIntoView({behavior:'smooth',block:'start'});buttons.prepend(button);
}
function workspaceMarkup(){
 const stats=riskStats(),saved=routine(),score=stats.risky?Math.max(35,82-stats.risky*9):82;
 return `<section class="card wide pro-workspace" id="proWorkspace">
  <div class="pro-hero"><div><span class="pro-label">✦ GitHub Protect Pro</span><h2 class="pro-title"><span>Your productive security workspace.</span></h2><p class="pro-copy">Turn separate safety checks into one organized routine with reports, reminders, device profiles, and a focused risk inbox. This is an interactive preview of the upcoming Pro experience.</p><div class="pro-actions"><button class="btn pro-primary" id="createRoutine" type="button">Create protection routine</button><button class="btn alt" id="proBuildReport" type="button">Export security report</button></div></div>
  <div class="pro-score"><div class="pro-score-ring">${score}</div><div><b>Security readiness</b><small>${stats.total?stats.total+' recent files reviewed':'Run a scan to personalize this score'}</small></div></div></div>
  <div class="pro-dashboard"><div class="pro-metrics"><div class="pro-metric"><span>FILES REVIEWED</span><b id="proFiles">${stats.total}</b></div><div class="pro-metric"><span>NEEDS REVIEW</span><b id="proReview">${stats.review+stats.risky}</b></div><div class="pro-metric"><span>ROUTINES</span><b id="proRoutines">${saved?1:0}</b></div><div class="pro-metric"><span>LOCAL REPORTS</span><b>${stats.total?1:0}</b></div></div>
  <div class="pro-productivity"><article class="pro-panel"><h3>Quick productivity</h3><p>Move from warning to action without digging through the full dashboard.</p><div class="pro-quick-grid"><button class="pro-quick" id="proQuickScan">⌕ Scan files now</button><button class="pro-quick" id="proQuickInbox">🔔 Open risk inbox</button><button class="pro-quick" id="proQuickRoutine">◷ ${saved?'Edit':'Plan'} routine</button><button class="pro-quick" id="proQuickReport">↧ Build report</button></div></article>
  <article class="pro-panel"><h3>Protection timeline</h3><p>Your activity stays in this browser.</p><div class="pro-timeline"><div class="pro-event"><span class="pro-event-dot"></span><div><strong>${stats.total?'Latest scan ready':'Ready for first scan'}</strong><small>${stats.total?stats.safe+' clear · '+(stats.review+stats.risky)+' need review':'Choose files or a folder to begin'}</small></div></div><div class="pro-event"><span class="pro-event-dot"></span><div><strong>${saved?'Routine planned':'No routine yet'}</strong><small>${saved?saved.frequency+' reminder · '+saved.name:'Create a simple repeatable security check'}</small></div></div></div></article></div></div>
 </section>`;
}
function plansMarkup(){return `<section class="card wide plans" id="plans"><div class="plans-head"><div><div class="eyebrow">Choose your protection level</div><h2>Simple now. Powerful when you need it.</h2><p>All essential checks remain free. Pro organizes advanced workflows, while Teams is built for shared protection.</p></div></div><div class="plan-grid">
 <article class="plan"><h3>Free</h3><div class="plan-price">₹0 <small>forever</small></div><p>Strong everyday checks for one device.</p><ul><li>31 local security tools</li><li>File and folder checks</li><li>Browser extension</li><li>Private local scanning</li><li>Basic exported reports</li></ul><button class="btn alt" type="button" disabled>Current plan</button><div class="plan-note">Available now</div></article>
 <article class="plan featured"><span class="plan-badge">Best experience</span><h3>Pro</h3><div class="plan-price">Coming soon</div><p>A faster, organized security workflow for power users.</p><ul><li>Everything in Free</li><li>Protection routines and reminders</li><li>Detailed report history</li><li>Device security profiles</li><li>Priority risk inbox</li><li>Advanced phishing insights</li><li>Priority feature updates</li></ul><button class="btn pro-primary" id="proInterest" type="button">Notify me at launch</button><div class="plan-note">Pricing will be announced before launch</div></article>
 <article class="plan"><h3>Teams</h3><div class="plan-price">Coming later</div><p>Shared visibility for families, schools, and small teams.</p><ul><li>Everything in Pro</li><li>Shared protection dashboard</li><li>Managed device profiles</li><li>Team report summaries</li><li>Central safety policies</li><li>Multiple member seats</li></ul><button class="btn alt" id="teamUpdates" type="button">Follow team updates</button><div class="plan-note">No checkout or payment is active yet</div></article>
 </div><div class="notice"><strong>Transparent launch:</strong> Pro and Teams are previews. No payment is collected on this website. Future billing should be managed by an adult account holder.</div></section>`}
function modalMarkup(){return `<div class="modal" id="proRoutineModal" role="dialog" aria-modal="true" aria-labelledby="proRoutineTitle"><div class="modal-box"><div class="modal-head"><div><div class="eyebrow">Pro productivity</div><h2 id="proRoutineTitle">Create a protection routine</h2></div><button class="close" id="closeProRoutine" aria-label="Close">×</button></div><p>Plan a repeatable check. The reminder is stored only in this browser and appears while the app is open.</p><div class="pro-modal-grid"><div class="pro-field"><label for="routineName">Routine name</label><input id="routineName" maxlength="50" value="Weekly download review"></div><div class="pro-field"><label for="routineFrequency">Frequency</label><select id="routineFrequency"><option>Every day</option><option selected>Every week</option><option>Every month</option></select></div><div class="pro-field"><label for="routineFocus">Focus</label><select id="routineFocus"><option>Downloads and installers</option><option>Suspicious links and messages</option><option>Complete security review</option></select></div></div><div class="pro-modal-note">Browsers cannot scan your computer silently. You always choose the files or folder, keeping you in control.</div><div class="buttons" style="margin-top:18px"><button class="btn pro-primary" id="saveRoutine" type="button">Save routine</button><button class="btn alt" id="cancelRoutine" type="button">Cancel</button></div><div id="routineSaved" style="margin-top:12px"></div></div></div>`}
function mount(){
 if($('#proWorkspace'))return;
 mountHeader();mountNav();
 const grid=$('.grid'),guides=$('#securityGuides');if(!grid)return;
 grid.insertAdjacentHTML('afterend',workspaceMarkup());
 const anchor=guides||$('#popularCheckers')||$('.notice');anchor?.insertAdjacentHTML('beforebegin',plansMarkup());
 document.body.insertAdjacentHTML('beforeend',modalMarkup());
 const saved=routine();if(saved){$('#routineName').value=saved.name;$('#routineFrequency').value=saved.frequency;$('#routineFocus').value=saved.focus}
 const showRoutine=()=>openModal('proRoutineModal');
 $('#createRoutine').onclick=showRoutine;$('#proQuickRoutine').onclick=showRoutine;
 $('#closeProRoutine').onclick=()=>closeModal('proRoutineModal');$('#cancelRoutine').onclick=()=>closeModal('proRoutineModal');
 $('#proRoutineModal').addEventListener('click',e=>{if(e.target.id==='proRoutineModal')closeModal('proRoutineModal')});
 $('#saveRoutine').onclick=()=>{const data={name:$('#routineName').value.trim()||'Security review',frequency:$('#routineFrequency').value,focus:$('#routineFocus').value,savedAt:Date.now()};localStorage.setItem(STORAGE.routine,JSON.stringify(data));$('#routineSaved').innerHTML='<span class="pro-success">✓ Routine saved on this device</span>';$('#proRoutines').textContent='1';$('#proQuickRoutine').textContent='◷ Edit routine';addAlert('Pro routine saved',data.name+' · '+data.frequency);setTimeout(()=>closeModal('proRoutineModal'),900)};
 $('#proBuildReport').onclick=downloadReport;$('#proQuickReport').onclick=downloadReport;
 $('#proQuickScan').onclick=()=>$('#fileTesting')?.scrollIntoView({behavior:'smooth',block:'start'});
 $('#proQuickInbox').onclick=()=>$('#notificationButton')?.click();
 $('#proInterest').onclick=()=>{localStorage.setItem(STORAGE.interest,'pro');$('#proInterest').textContent='Launch interest saved ✓';$('#proInterest').disabled=true;addAlert('Pro launch interest saved','Follow upgrade news for the launch announcement.')};
 if(localStorage.getItem(STORAGE.interest)==='pro'){$('#proInterest').textContent='Launch interest saved ✓';$('#proInterest').disabled=true}
 $('#teamUpdates').onclick=()=>window.open('https://www.youtube.com/@Amazing_Armaan','_blank','noopener,noreferrer');
 document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal('proRoutineModal')});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
