(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const css=document.createElement('style');css.textContent=`
.product-switcher{display:flex;gap:7px;align-items:center}.product-link{display:inline-flex;align-items:center;gap:5px;min-height:36px;padding:7px 11px;border:1px solid #334b6b;border-radius:11px;background:#14233a;color:#dcecff;text-decoration:none;font-size:12px;font-weight:900}.product-link:hover{border-color:var(--blue);transform:translateY(-1px)}.product-link.pro{border-color:#7766bf;background:linear-gradient(135deg,#34265f,#123453)}.product-link.teams{border-color:#277b77;background:linear-gradient(135deg,#0b3a3c,#113253)}
.edition-picker{margin-top:20px;padding:28px;border-color:#344a67;background:linear-gradient(150deg,#111c30,#090f1b)}.edition-picker h2{font-size:clamp(25px,4vw,38px);letter-spacing:-.035em}.edition-picker>p{max-width:720px}.edition-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:13px;margin-top:18px}.edition{display:flex;flex-direction:column;min-height:250px;padding:20px;border:1px solid #30435f;border-radius:17px;background:#09111e}.edition.pro{border-color:#7766bf;background:linear-gradient(150deg,rgba(72,46,127,.55),#0b1727)}.edition.teams{border-color:#277b77;background:linear-gradient(150deg,rgba(15,85,82,.45),#0b1727)}.edition h3{margin:0;font-size:21px}.edition ul{display:grid;gap:7px;margin:5px 0 20px;padding:0;list-style:none;color:#c7d7e9}.edition li:before{content:'✓';margin-right:8px;color:var(--green);font-weight:900}.edition .btn{display:block;margin-top:auto;text-align:center;text-decoration:none}.edition-current{margin-top:auto;padding:11px;border:1px solid #315071;border-radius:11px;color:#9fb4cd;text-align:center;font-weight:850}.edition-note{margin-top:14px;color:var(--muted);font-size:12px;text-align:center}@media(max-width:760px){.edition-grid{grid-template-columns:1fr}.product-link span{display:none}.product-link{width:38px;justify-content:center;padding:6px}}
`;document.head.append(css);
function mount(){if($('#editionPicker'))return;const header=$('header .buttons');if(header){const nav=document.createElement('nav');nav.className='product-switcher';nav.setAttribute('aria-label','GitHub Protect editions');nav.innerHTML='<a class="product-link" href="./">🛡️ <span>Free</span></a><a class="product-link pro" href="./pro/">✦ <span>Pro</span></a><a class="product-link teams" href="./teams/">👥 <span>Teams</span></a>';header.prepend(nav)}const grid=$('.grid');if(!grid)return;grid.insertAdjacentHTML('afterend',`<section class="card wide edition-picker" id="editionPicker"><div class="eyebrow">GitHub Protect editions</div><h2>Three products. Three focused workspaces.</h2><p>The Free scanner stays focused here. Pro and Teams now open as complete separate products with their own design, dashboard, and features.</p><div class="edition-grid"><article class="edition"><h3>🛡️ Free</h3><p>Private checks for one device.</p><ul><li>31 local tools</li><li>File and folder checks</li><li>Browser extension</li></ul><div class="edition-current">You are here</div></article><article class="edition pro"><h3>✦ Pro</h3><p>A premium personal command centre.</p><ul><li>Routines and reminders</li><li>Security readiness</li><li>Detailed reports</li></ul><a class="btn" href="./pro/">Open Pro page →</a></article><article class="edition teams"><h3>👥 Teams</h3><p>A shared security hub for groups.</p><ul><li>Team risk overview</li><li>Shared policies</li><li>Member activity</li></ul><a class="btn" href="./teams/">Open Teams page →</a></article></div><div class="edition-note">Pro and Teams are previews. No payment or checkout is active yet.</div></section>`)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
