(()=>{
const VERSION='2.0.0',KEY='githubProtectorSecurityData';
const riskyExt=new Set(['exe','msi','bat','cmd','com','scr','ps1','vbs','vbe','js','jse','wsf','hta','jar','reg','apk','dmg','pkg','sh']);
const permissionRisk={history:5,'webRequest':5,'webRequestBlocking':5,'<all_urls>':5,debugger:5,nativeMessaging:5,downloads:3,clipboardRead:4,clipboardWrite:2,cookies:4,geolocation:3,management:4,tabs:2,notifications:1,storage:1,camera:3,microphone:3};
const officialStores=['chromewebstore.google.com','play.google.com','apps.microsoft.com','apps.apple.com','addons.mozilla.org','microsoftedge.microsoft.com','addons.opera.com','galaxystore.samsung.com','galaxy.store','appgallery.huawei.com','amazon.com','www.amazon.com'];
const $=(s,r=document)=>r.querySelector(s), el=(tag,props={},...kids)=>{const n=document.createElement(tag);Object.assign(n,props);for(const k of kids)n.append(k?.nodeType?k:document.createTextNode(String(k??'')));return n};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{trusted:[],blocked:[],checks:0}}catch{return{trusted:[],blocked:[],checks:0}}}let data=load();
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function hostOf(raw){try{return new URL(raw.includes('://')?raw:'https://'+raw).hostname.toLowerCase()}catch{return''}}
function listValues(id){return $('#'+id).value.split(/\r?\n|,/).map(x=>x.trim().toLowerCase()).filter(Boolean)}
function levelBadge(level){return '<span class="tool-badge '+level+'">'+level.toUpperCase()+'</span>'}
function urlScore(raw){let score=0,reasons=[];try{const u=new URL(raw.includes('://')?raw:'https://'+raw),h=u.hostname.toLowerCase();if(u.protocol!=='https:'){score+=20;reasons.push('No HTTPS')}if(/^\d+\.\d+\.\d+\.\d+$/.test(h)){score+=35;reasons.push('Raw IP address')}if(h.includes('xn--')){score+=25;reasons.push('Encoded domain')}if(h.split('.').length>4){score+=10;reasons.push('Many subdomains')}if(raw.includes('@')){score+=40;reasons.push('Hidden-destination pattern')}if(/login|verify|urgent|wallet|gift|prize|secure-update/i.test(h)){score+=20;reasons.push('Pressure words in domain')}if(/\.(exe|msi|apk|dmg|pkg)(\?|#|$)/i.test(u.pathname)){score+=25;reasons.push('Direct installer download')}if(data.blocked.some(x=>h===x||h.endsWith('.'+x))){score=100;reasons.push('On your blocked list')}if(data.trusted.some(x=>h===x||h.endsWith('.'+x))){score=Math.max(0,score-20);reasons.push('On your trusted list')}return{score:Math.min(score,100),reasons,host:h,url:u.href}}catch{return{score:100,reasons:['Invalid URL'],host:'',url:''}}}
function renderHealth(){let scans=[];try{scans=JSON.parse(localStorage.getItem('githubProtectLastScan'))||[]}catch{}let alerts=[];try{alerts=JSON.parse(localStorage.getItem('githubProtectAlerts'))||[]}catch{}$('#healthValues').innerHTML='<div class="health-cell"><b>'+VERSION+'</b>App version</div><div class="health-cell"><b>'+scans.length+'</b>Last scan files</div><div class="health-cell"><b>'+alerts.length+'</b>Security alerts</div><div class="health-cell"><b>'+data.blocked.length+'</b>Blocked entries</div>';$('#healthTime').textContent='Dashboard refreshed '+new Date().toLocaleTimeString()}
function result(id,title,level,details){const n=$('#'+id);n.innerHTML=levelBadge(level)+' <strong>'+title+'</strong><p></p>';n.querySelector('p').textContent=details;data.checks++;save();renderHealth()}
function parseZipNames(bytes){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),dec=new TextDecoder(),names=[];for(let i=0;i+46<=bytes.length;i++){if(v.getUint32(i,true)!==0x02014b50)continue;const nl=v.getUint16(i+28,true),el=v.getUint16(i+30,true),cl=v.getUint16(i+32,true);if(i+46+nl>bytes.length)break;names.push(dec.decode(bytes.subarray(i+46,i+46+nl)));i+=45+nl+el+cl}return names}
function mount(){
 const grid=$('.grid'),notice=$('main > .notice');if(!grid||$('#securitySuite'))return;
 const section=el('section',{id:'securitySuite',className:'card wide security-suite'});
 section.innerHTML=`
 <div class="suite-head"><div><div class="eyebrow">Advanced protection</div><h2>Security Tools Centre</h2><p>Ten extra defensive tools. Checks run locally unless a live threat feed is clearly stated.</p></div><button class="btn alt mini" id="refreshHealth">Refresh status</button></div>
 <div class="health-grid" id="healthValues"></div><small id="healthTime"></small>
 <div class="tool-grid">
  <div class="tool"><h3>1. Permission Risk Inspector</h3><p>Upload an extension <code>manifest.json</code> or paste permission names.</p><input type="file" id="manifestFile" accept=".json,application/json"><textarea id="permissionText" placeholder="history, downloads, tabs, &lt;all_urls&gt;"></textarea><button class="btn mini" id="checkPermissions">Inspect permissions</button><div class="tool-result" id="permissionResult"></div></div>
  <div class="tool"><h3>2. Publisher & Store Check</h3><p>Compare the listing, publisher website, and official store domain.</p><input id="publisherListing" placeholder="App-store listing URL"><input id="publisherSite" placeholder="Publisher website URL"><button class="btn mini" id="checkPublisher">Check publisher</button><div class="tool-result" id="publisherResult"></div></div>
  <div class="tool"><h3>3. Download Source Score</h3><p>Score a download or webpage address before opening it.</p><input id="sourceUrl" placeholder="Paste download URL"><button class="btn mini" id="scoreSource">Score source</button><div class="tool-result" id="sourceResult"></div></div>
  <div class="tool"><h3>4. Fake Update Detector</h3><p>Paste an update link and the message shown on the page.</p><input id="updateUrl" placeholder="Update URL"><textarea id="updateMessage" placeholder="Paste the update message"></textarea><button class="btn mini" id="checkFakeUpdate">Check update</button><div class="tool-result" id="updateResult"></div></div>
  <div class="tool"><h3>5. QR Link Scanner</h3><p>Select a QR-code image to reveal and inspect its link.</p><input type="file" id="qrFile" accept="image/*"><button class="btn mini" id="scanQr">Scan QR</button><div class="tool-result" id="qrResult"></div></div>
  <div class="tool"><h3>6. ZIP Contents Scanner</h3><p>Reads ZIP filenames without extracting or running anything.</p><input type="file" id="zipFile" accept=".zip,application/zip"><button class="btn mini" id="scanZip">Inspect ZIP</button><div class="tool-result" id="zipResult"></div></div>
  <div class="tool"><h3>7. Extension Permission Review</h3><p>The manifest inspector highlights newly dangerous permissions. Browser rules prevent silently reading other extensions.</p><button class="btn alt mini" id="jumpPermissions">Review a manifest</button></div>
  <div class="tool"><h3>8. Security Health Dashboard</h3><p>Tracks local scans, warnings, lists, and installed tool version.</p><button class="btn alt mini" id="refreshHealth2">Refresh dashboard</button></div>
  <div class="tool"><h3>9. Trusted & Blocked Lists</h3><p>One domain per line. These lists stay in this browser.</p><textarea id="trustedList" placeholder="Trusted domains"></textarea><textarea id="blockedList" placeholder="Blocked domains"></textarea><button class="btn mini" id="saveLists">Save lists</button><div class="tool-result" id="listResult"></div></div>
  <div class="tool"><h3>10. Update Checker</h3><p>Checks the published release file for a newer app or extension.</p><button class="btn mini" id="checkUpdates">Check updates</button><div class="tool-result" id="updateCheckResult"></div></div>
 </div>`;
 grid.after(section);data.trusted=data.trusted||[];data.blocked=data.blocked||[];$('#trustedList').value=data.trusted.join('\n');$('#blockedList').value=data.blocked.join('\n');renderHealth();
 $('#refreshHealth').onclick=$('#refreshHealth2').onclick=renderHealth;
 $('#manifestFile').onchange=async e=>{try{const m=JSON.parse(await e.target.files[0].text()),perms=[...(m.permissions||[]),...(m.host_permissions||[])];$('#permissionText').value=perms.join(', ')}catch{result('permissionResult','Invalid manifest','danger','The selected file is not valid JSON.')}};
 $('#checkPermissions').onclick=()=>{const perms=listValues('permissionText'),findings=perms.map(p=>({p,r:permissionRisk[p]||(/^https?:\/\/\*\//.test(p)?4:1)})).sort((a,b)=>b.r-a.r),max=findings[0]?.r||0;result('permissionResult',max>=5?'High-access permissions found':max>=3?'Review these permissions':'Low obvious permission risk',max>=5?'danger':max>=3?'warn':'safe',findings.length?findings.map(x=>x.p+' ('+x.r+'/5)').join(' • '):'No permissions entered.')};
 $('#checkPublisher').onclick=()=>{const listing=hostOf($('#publisherListing').value),site=hostOf($('#publisherSite').value),official=officialStores.some(h=>listing===h||listing.endsWith('.'+h));let level=official?'safe':'warn',notes=[official?'Official store domain':'Listing is not on a recognised official store'];if(site&&listing&&site===listing)notes.push('Publisher website equals listing host');if(!site)notes.push('Publisher website missing');result('publisherResult',official?'Store verified; publisher still needs review':'Publisher needs verification',level,notes.join(' • '))};
 $('#scoreSource').onclick=()=>{const r=urlScore($('#sourceUrl').value),level=r.score>=60?'danger':r.score>=25?'warn':'safe';result('sourceResult','Risk score '+r.score+'/100',level,r.reasons.join(' • ')||'No obvious URL warning signs detected.')};
 $('#checkFakeUpdate').onclick=()=>{const r=urlScore($('#updateUrl').value),msg=$('#updateMessage').value;let score=r.score,reasons=[...r.reasons];if(/urgent|immediately|virus detected|expired|must update|act now/i.test(msg)){score+=30;reasons.push('Uses urgent or frightening language')}if(/disable.*(antivirus|security)|allow.*notification/i.test(msg)){score+=45;reasons.push('Asks to weaken protection')}const level=score>=60?'danger':score>=25?'warn':'safe';result('updateResult',score>=60?'Likely fake or unsafe update':score>=25?'Update needs verification':'No obvious fake-update signs',level,reasons.join(' • ')||'Use the app’s built-in update menu rather than webpage popups.')};
 $('#scanQr').onclick=async()=>{const file=$('#qrFile').files[0];if(!file)return result('qrResult','Choose a QR image','warn','No image selected.');if(!('BarcodeDetector'in window))return result('qrResult','QR scanning unavailable','warn','This browser does not support the BarcodeDetector API. Try current Chrome or Edge.');try{const codes=await new BarcodeDetector({formats:['qr_code']}).detect(await createImageBitmap(file));if(!codes.length)return result('qrResult','No QR code found','warn','Try a clearer image.');const raw=codes[0].rawValue,r=urlScore(raw),level=r.score>=60?'danger':r.score>=25?'warn':'safe';result('qrResult','QR content: '+raw,level,r.reasons.join(' • ')||'No obvious URL warning signs detected.')}catch(e){result('qrResult','QR scan failed','danger',e.message)}};
 $('#scanZip').onclick=async()=>{const file=$('#zipFile').files[0];if(!file)return result('zipResult','Choose a ZIP file','warn','No ZIP selected.');try{const names=parseZipNames(new Uint8Array(await file.arrayBuffer()));if(!names.length)return result('zipResult','ZIP could not be inspected','warn','No standard ZIP directory entries were found.');const risky=names.filter(n=>{const parts=n.toLowerCase().split('.'),x=parts.at(-1);return riskyExt.has(x)||(parts.length>2&&riskyExt.has(x))});result('zipResult',risky.length?risky.length+' risky item(s) found':'No risky filenames found',risky.length?'danger':'safe',risky.slice(0,20).join(' • ')||names.length+' entries checked.')}catch(e){result('zipResult','ZIP scan failed','danger',e.message)}};
 $('#jumpPermissions').onclick=()=>{$('#manifestFile').scrollIntoView({behavior:'smooth',block:'center'});$('#manifestFile').focus()};
 $('#saveLists').onclick=()=>{data.trusted=listValues('trustedList');data.blocked=listValues('blockedList');save();renderHealth();result('listResult','Lists saved','safe',data.trusted.length+' trusted • '+data.blocked.length+' blocked')};
 $('#checkUpdates').onclick=async()=>{try{const r=await fetch('./latest-version.json',{cache:'no-store'}),v=await r.json();const newer=v.app!==VERSION;result('updateCheckResult',newer?'Update available':'App is current',newer?'warn':'safe','Installed tools: '+VERSION+' • Latest app: '+v.app+' • Extension: '+v.extension)}catch{result('updateCheckResult','Update check unavailable','warn','The version file could not be reached.')}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();