(()=>{
const VERSION='4.6.1',KEY='githubProtectorSecurityData';
const riskyExt=new Set(['exe','msi','bat','cmd','com','scr','ps1','vbs','vbe','js','jse','wsf','hta','jar','reg','apk','dmg','pkg','sh']);
const permissionRisk={history:5,'webRequest':5,'webRequestBlocking':5,'<all_urls>':5,debugger:5,nativeMessaging:5,downloads:3,clipboardRead:4,clipboardWrite:2,cookies:4,geolocation:3,management:4,tabs:2,notifications:1,storage:1,camera:3,microphone:3};
const officialStores=['chromewebstore.google.com','play.google.com','apps.microsoft.com','apps.apple.com','addons.mozilla.org','microsoftedge.microsoft.com','addons.opera.com','galaxystore.samsung.com','galaxy.store','appgallery.huawei.com','amazon.com','www.amazon.com'];
const $=(s,r=document)=>r.querySelector(s), el=(tag,props={},...kids)=>{const n=document.createElement(tag);Object.assign(n,props);for(const k of kids)n.append(k?.nodeType?k:document.createTextNode(String(k??'')));return n};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{trusted:[],blocked:[],checks:0}}catch{return{trusted:[],blocked:[],checks:0}}}let data=load();
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function hostOf(raw){try{return new URL(raw.includes('://')?raw:'https://'+raw).hostname.toLowerCase()}catch{return''}}
function listValues(id){return $('#'+id).value.split(/\r?\n|,/).map(x=>x.trim().toLowerCase()).filter(Boolean)}
function levelBadge(level){return '<span class="tool-badge '+level+'">'+level.toUpperCase()+'</span>'}
function urlScore(raw){let score=0,reasons=[];try{const u=new URL(raw.includes('://')?raw:'https://'+raw),h=u.hostname.toLowerCase();if(u.protocol!=='https:'){score+=20;reasons.push('No HTTPS')}if(/^\d+\.\d+\.\d+\.\d+$/.test(h)){score+=35;reasons.push('Raw IP address')}if(h.includes('xn--')){score+=25;reasons.push('Encoded domain')}if(h.split('.').length>4){score+=10;reasons.push('Many subdomains')}if(raw.includes('@')){score+=40;reasons.push('Hidden-destination pattern')}if(/login|verify|urgent|wallet|gift|prize|secure-update/i.test(h)){score+=20;reasons.push('Pressure words in domain')}if(/\.(exe|msi|apk|dmg|pkg)(\?|#|$)/i.test(u.pathname)){score+=25;reasons.push('Direct installer download')}if(data.blocked.some(x=>h===x||h.endsWith('.'+x))){score=100;reasons.push('On your blocked list')}if(data.trusted.some(x=>h===x||h.endsWith('.'+x))){score=Math.max(0,score-20);reasons.push('On your trusted list')}return{score:Math.min(score,100),reasons,host:h,url:u.href}}catch{return{score:100,reasons:['Invalid URL'],host:'',url:''}}}
function renderHealth(){let scans=[];try{scans=JSON.parse(localStorage.getItem('githubProtectLastScan'))||[]}catch{}let alerts=[];try{alerts=JSON.parse(localStorage.getItem('githubProtectAlerts'))||[]}catch{}$('#healthValues').innerHTML='<div class="health-cell"><b>'+VERSION+'</b>App version</div><div class="health-cell"><b>'+scans.length+'</b>Last scan files</div><div class="health-cell"><b>'+alerts.length+'</b>Security alerts</div><div class="health-cell"><b>'+data.blocked.length+'</b>Blocked entries</div>';$('#healthTime').textContent='Dashboard refreshed '+new Date().toLocaleTimeString()}
function result(id,title,level,details){const n=$('#'+id);n.innerHTML=levelBadge(level)+' <strong>'+title+'</strong><p></p>';n.querySelector('p').textContent=details;data.checks++;save();renderHealth()}
function parseZipNames(bytes){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),dec=new TextDecoder(),names=[];for(let i=0;i+46<=bytes.length;i++){if(v.getUint32(i,true)!==0x02014b50)continue;const nl=v.getUint16(i+28,true),el=v.getUint16(i+30,true),cl=v.getUint16(i+32,true);if(i+46+nl>bytes.length)break;names.push(dec.decode(bytes.subarray(i+46,i+46+nl)));i+=45+nl+el+cl}return names}
function mount(){
 const grid=$('.grid'),notice=$('main > .notice');if(!grid||$('#securitySuite'))return;
 const section=el('section',{id:'securitySuite',className:'card wide security-suite'});
 section.innerHTML=`
 <div class="suite-head"><div><div class="eyebrow">Advanced protection</div><h2>Security Tools Centre</h2><p>Ten extra defensive tools. Checks run locally unless a live threat feed is clearly stated.</p></div><button class="btn alt mini" id="refreshHealth">Refresh status</button></div>
 <div class="health-grid" id="healthValues"></div><small id="healthTime"></small>
 <div class="tool-grid">
  <div class="tool"><h3>1. Permission Risk Inspector</h3><p>Upload an extension <code>manifest.json</code> or paste permission names.</p><input type="file" id="manifestFile" accept=".json,application/json"><textarea id="permissionText" placeholder="history, downloads, tabs, &lt;all_urls&gt;"></textarea><button class="btn mini" id="checkPermissions">Inspect permissions</button><div class="tool-result" id="permissionResult"></div></div>
  <div class="tool"><h3>2. Publisher & Store Check</h3><p>Compare the listing, publisher website, and official store domain.</p><input id="publisherListing" placeholder="App-store listing URL"><input id="publisherSite" placeholder="Publisher website URL"><button class="btn mini" id="checkPublisher">Check publisher</button><div class="tool-result" id="publisherResult"></div></div>
  <div class="tool"><h3>3. Download Source Score</h3><p>Score a download or webpage address before opening it.</p><input id="sourceUrl" placeholder="Paste download URL"><button class="btn mini" id="scoreSource">Score source</button><div class="tool-result" id="sourceResult"></div></div>
  <div class="tool"><h3>4. Fake Update Detector</h3><p>Paste an update link and the message shown on the page.</p><input id="updateUrl" placeholder="Update URL"><textarea id="updateMessage" placeholder="Paste the update message"></textarea><button class="btn mini" id="checkFakeUpdate">Check update</button><div class="tool-result" id="updateResult"></div></div>
  <div class="tool"><h3>5. QR Link Scanner</h3><p>Select a QR-code image to reveal and inspect its link.</p><input type="file" id="qrFile" accept="image/*"><button class="btn mini" id="scanQr">Scan QR</button><div class="tool-result" id="qrResult"></div></div>
  <div class="tool"><h3>6. ZIP Contents Scanner</h3><p>Reads ZIP filenames without extracting or running anything.</p><input type="file" id="zipFile" accept=".zip,application/zip"><button class="btn mini" id="scanZip">Inspect ZIP</button><div class="tool-result" id="zipResult"></div></div>
  <div class="tool"><h3>7. Extension Permission Review</h3><p>The manifest inspector highlights newly dangerous permissions. Browser rules prevent silently reading other extensions.</p><button class="btn alt mini" id="jumpPermissions">Review a manifest</button></div>
  <div class="tool"><h3>8. Security Health Dashboard</h3><p>Tracks local scans, warnings, lists, and installed tool version.</p><button class="btn alt mini" id="refreshHealth2">Refresh dashboard</button></div>
  <div class="tool"><h3>9. Trusted & Blocked Lists</h3><p>One domain per line. These lists stay in this browser.</p><textarea id="trustedList" placeholder="Trusted domains"></textarea><textarea id="blockedList" placeholder="Blocked domains"></textarea><button class="btn mini" id="saveLists">Save lists</button><div class="tool-result" id="listResult"></div></div>
  <div class="tool"><h3>10. Update Checker</h3><p>Checks the published release file for a newer app or extension.</p><button class="btn mini" id="checkUpdates">Check updates</button><div class="tool-result" id="updateCheckResult"></div></div>
 </div>`;
 grid.after(section);data.trusted=data.trusted||[];data.blocked=data.blocked||[];$('#trustedList').value=data.trusted.join('\n');$('#blockedList').value=data.blocked.join('\n');renderHealth();
 $('#refreshHealth').onclick=$('#refreshHealth2').onclick=renderHealth;
 $('#manifestFile').onchange=async e=>{try{const m=JSON.parse(await e.target.files[0].text()),perms=[...(m.permissions||[]),...(m.host_permissions||[])];$('#permissionText').value=perms.join(', ')}catch{result('permissionResult','Invalid manifest','danger','The selected file is not valid JSON.')}};
 $('#checkPermissions').onclick=()=>{const perms=listValues('permissionText'),findings=perms.map(p=>({p,r:permissionRisk[p]||(/^https?:\/\/\*\//.test(p)?4:1)})).sort((a,b)=>b.r-a.r),max=findings[0]?.r||0;result('permissionResult',max>=5?'High-access permissions found':max>=3?'Review these permissions':'Low obvious permission risk',max>=5?'danger':max>=3?'warn':'safe',findings.length?findings.map(x=>x.p+' ('+x.r+'/5)').join(' • '):'No permissions entered.')};
 $('#checkPublisher').onclick=()=>{const listing=hostOf($('#publisherListing').value),site=hostOf($('#publisherSite').value),official=officialStores.some(h=>listing===h||listing.endsWith('.'+h));let level=official?'safe':'warn',notes=[official?'Official store domain':'Listing is not on a recognised official store'];if(site&&listing&&site===listing)notes.push('Publisher website equals listing host');if(!site)notes.push('Publisher website missing');result('publisherResult',official?'Store verified; publisher still needs review':'Publisher needs verification',level,notes.join(' • '))};
 $('#scoreSource').onclick=()=>{const r=urlScore($('#sourceUrl').value),level=r.score>=60?'danger':r.score>=25?'warn':'safe';result('sourceResult','Risk score '+r.score+'/100',level,r.reasons.join(' • ')||'No obvious URL warning signs detected.')};
 $('#checkFakeUpdate').onclick=()=>{const r=urlScore($('#updateUrl').value),msg=$('#updateMessage').value;let score=r.score,reasons=[...r.reasons];if(/urgent|immediately|virus detected|expired|must update|act now/i.test(msg)){score+=30;reasons.push('Uses urgent or frightening language')}if(/disable.*(antivirus|security)|allow.*notification/i.test(msg)){score+=45;reasons.push('Asks to weaken protection')}const level=score>=60?'danger':score>=25?'warn':'safe';result('updateResult',score>=60?'Likely fake or unsafe update':score>=25?'Update needs verification':'No obvious fake-update signs',level,reasons.join(' • ')||'Use the app’s built-in update menu rather than webpage popups.')};
 $('#scanQr').onclick=async()=>{const file=$('#qrFile').files[0];if(!file)return result('qrResult','Choose a QR image','warn','No image selected.');if(!('BarcodeDetector'in window))return result('qrResult','QR scanning unavailable','warn','This browser does not support the BarcodeDetector API. Try current Chrome or Edge.');try{const codes=await new BarcodeDetector({formats:['qr_code']}).detect(await createImageBitmap(file));if(!codes.length)return result('qrResult','No QR code found','warn','Try a clearer image.');const raw=codes[0].rawValue,r=urlScore(raw),level=r.score>=60?'danger':r.score>=25?'warn':'safe';result('qrResult','QR content: '+raw,level,r.reasons.join(' • ')||'No obvious URL warning signs detected.')}catch(e){result('qrResult','QR scan failed','danger',e.message)}};
 $('#scanZip').onclick=async()=>{const file=$('#zipFile').files[0];if(!file)return result('zipResult','Choose a ZIP file','warn','No ZIP selected.');try{const names=parseZipNames(new Uint8Array(await file.arrayBuffer()));if(!names.length)return result('zipResult','ZIP could not be inspected','warn','No standard ZIP directory entries were found.');const risky=names.filter(n=>{const parts=n.toLowerCase().split('.'),x=parts.at(-1);return riskyExt.has(x)||(parts.length>2&&riskyExt.has(x))});result('zipResult',risky.length?risky.length+' risky item(s) found':'No risky filenames found',risky.length?'danger':'safe',risky.slice(0,20).join(' • ')||names.length+' entries checked.')}catch(e){result('zipResult','ZIP scan failed','danger',e.message)}};
 $('#jumpPermissions').onclick=()=>{$('#manifestFile').scrollIntoView({behavior:'smooth',block:'center'});$('#manifestFile').focus()};
 $('#saveLists').onclick=()=>{data.trusted=listValues('trustedList');data.blocked=listValues('blockedList');save();renderHealth();result('listResult','Lists saved','safe',data.trusted.length+' trusted • '+data.blocked.length+' blocked')};
 $('#checkUpdates').onclick=async()=>{try{const r=await fetch('./latest-version.json',{cache:'no-store'}),v=await r.json();const newer=v.app!==VERSION;result('updateCheckResult',newer?'Update available':'App is current',newer?'warn':'safe','Installed tools: '+VERSION+' • Latest app: '+v.app+' • Extension: '+v.extension)}catch{result('updateCheckResult','Update check unavailable','warn','The version file could not be reached.')}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
;(()=>{
const KEY='githubProtectorSecurityData',REM='githubProtectorReminder',$=(s,r=document)=>r.querySelector(s);
const risky=new Set(['exe','msi','bat','cmd','com','scr','ps1','vbs','js','jse','wsf','hta','jar','reg','apk','dmg','pkg','sh']);
const brands=['google.com','microsoft.com','apple.com','amazon.com','github.com','paypal.com','facebook.com','instagram.com','netflix.com','discord.com'];
function get(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}}function put(d){localStorage.setItem(KEY,JSON.stringify(d))}
function host(v){try{return new URL(v.includes('://')?v:'https://'+v).hostname.toLowerCase()}catch{return''}}
function show(id,title,level,detail){const n=$('#'+id);n.innerHTML='<span class="tool-badge '+level+'">'+level.toUpperCase()+'</span> <strong></strong><p></p>';n.querySelector('strong').textContent=title;n.querySelector('p').textContent=detail}
function lev(a,b){const r=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let p=r[0];r[0]=i;for(let j=1;j<=b.length;j++){const o=r[j];r[j]=Math.min(r[j]+1,r[j-1]+1,p+(a[i-1]===b[j-1]?0:1));p=o}}return r[b.length]}
function inspect(raw,strict){let score=0,why=[];try{const u=new URL(raw.includes('://')?raw:'https://'+raw),h=u.hostname.toLowerCase(),base=h.split('.').slice(-2).join('.');if(u.protocol!=='https:'){score+=strict?30:20;why.push('not HTTPS')}if(/^\d+\.\d+\.\d+\.\d+$/.test(h)){score+=35;why.push('raw IP address')}if(h.includes('xn--')){score+=30;why.push('encoded domain')}if(h.split('.').length>4){score+=strict?18:10;why.push('many subdomains')}if(raw.includes('@')){score+=40;why.push('hidden-destination pattern')}if(/login|verify|urgent|wallet|gift|prize|security-check|update-now/i.test(h+u.pathname)){score+=strict?30:20;why.push('pressure or account words')}for(const b of brands)if(base!==b&&lev(base,b)<=2){score+=45;why.push('resembles '+b);break}const d=get();if((d.blocked||[]).some(x=>h===x||h.endsWith('.'+x))){score=100;why.push('blocked by you')}if((d.trusted||[]).some(x=>h===x||h.endsWith('.'+x))){score=Math.max(0,score-25);why.push('trusted by you')}return{score:Math.min(100,score),why,host:h,href:u.href}}catch{return{score:100,why:['invalid URL'],host:'',href:''}}}
function level(s){return s>=60?'danger':s>=25?'warn':'safe'}
async function hash(f){const b=await crypto.subtle.digest('SHA-256',await f.arrayBuffer());return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function redirects(raw){let a=[],v=raw;for(let i=0;i<6;i++){let u;try{u=new URL(v.includes('://')?v:'https://'+v)}catch{break}a.push(u.href);let n='';for(const k of ['url','u','target','redirect','redirect_url','dest','destination','continue','next'])if(u.searchParams.get(k)){n=u.searchParams.get(k);break}if(!n||n===v)break;try{v=decodeURIComponent(n)}catch{v=n}}return a}
function record(name,l,details){const d=get();d.recentFindings=Array.isArray(d.recentFindings)?d.recentFindings:[];d.recentFindings.unshift({name,level:l,details,time:new Date().toISOString()});d.recentFindings=d.recentFindings.slice(0,50);put(d)}
function download(name,obj){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function mount(){if($('#securitySuite2')||!$('#securitySuite'))return;const s=document.createElement('section');s.id='securitySuite2';s.className='card wide security-suite';
s.innerHTML='<div class="suite-head"><div><div class="eyebrow">Protection expansion</div><h2>Security Tools Centre — More Protection</h2><p>Ten more defensive tools. Files stay on your device and are never silently uploaded.</p></div><span class="tool-badge safe">v3.0</span></div><div class="tool-grid">'+
'<div class="tool"><h3>11. Download History Scanner</h3><p>Select recent downloads for local review.</p><input type="file" id="historyFiles" multiple><button class="btn mini" id="scanHistory">Review downloads</button><div class="tool-result" id="historyResult"></div></div>'+
'<div class="tool"><h3>12. File Hash Reputation</h3><p>Create a local SHA-256 fingerprint.</p><input type="file" id="hashFile"><button class="btn mini" id="hashBtn">Create fingerprint</button><button class="btn alt mini" id="copyHash" disabled>Copy hash</button><div class="tool-result" id="hashResult"></div></div>'+
'<div class="tool"><h3>13. Phishing Page Detector</h3><p>Check an address for fake-login signals.</p><input id="phishUrl" placeholder="Paste page URL"><button class="btn mini" id="phishBtn">Inspect address</button><div class="tool-result" id="phishResult"></div></div>'+
'<div class="tool"><h3>14. Typosquatting Protection</h3><p>Detect domains resembling popular sites.</p><input id="typoDomain" placeholder="example.com"><button class="btn mini" id="typoBtn">Check domain</button><div class="tool-result" id="typoResult"></div></div>'+
'<div class="tool"><h3>15. Redirect Chain Inspector</h3><p>Decode redirect parameters without visiting them.</p><input id="redirectUrl" placeholder="Paste redirect URL"><button class="btn mini" id="redirectBtn">Decode redirects</button><div class="tool-result" id="redirectResult"></div></div>'+
'<div class="tool"><h3>16. Data-Breach Checker</h3><p>Continue safely to the official breach checker. Your address is not stored here.</p><input id="breachEmail" type="email" autocomplete="off" placeholder="name@example.com"><button class="btn mini" id="breachBtn">Open official checker</button><div class="tool-result" id="breachResult"></div></div>'+
'<div class="tool"><h3>17. Security Report Export</h3><p>Export settings and recent findings, excluding file contents.</p><button class="btn mini" id="reportBtn">Download report</button><div class="tool-result" id="reportResult"></div></div>'+
'<div class="tool"><h3>18. Security Reminders</h3><p>Schedule checks while the app is used.</p><select id="reminderDays"><option value="1">Daily</option><option value="7" selected>Weekly</option><option value="30">Monthly</option></select><button class="btn mini" id="reminderBtn">Set reminder</button><div class="tool-result" id="reminderResult"></div></div>'+
'<div class="tool"><h3>19. Protected Browsing Mode</h3><p>Enable stricter local warnings.</p><label><input type="checkbox" id="strictMode"> Stricter scoring</label><div class="tool-result" id="strictResult"></div></div>'+
'<div class="tool"><h3>20. Backup & Restore</h3><p>Move settings and findings between devices.</p><button class="btn mini" id="backupBtn">Download backup</button><input type="file" id="restoreFile" accept=".json,application/json"><button class="btn alt mini" id="restoreBtn">Restore backup</button><div class="tool-result" id="backupResult"></div></div></div>';
$('#securitySuite').after(s);$('#strictMode').checked=!!get().strictMode;
$('#scanHistory').onclick=()=>{const fs=[...$('#historyFiles').files];if(!fs.length)return show('historyResult','Choose downloads','warn','Browser rules require you to select them.');const bad=fs.filter(f=>{const x=f.name.toLowerCase().split('.').pop();return risky.has(x)||/\.(pdf|jpg|png|docx?)\.(exe|scr|js)$/i.test(f.name)}),detail=fs.length+' files checked'+(bad.length?' • Review: '+bad.slice(0,8).map(f=>f.name).join(', '):' • No risky filename extensions');show('historyResult',bad.length?bad.length+' need review':'Downloads look ordinary',bad.length?'warn':'safe',detail);record('Download review',bad.length?'warn':'safe',detail)};
let lastHash='';$('#hashBtn').onclick=async()=>{const f=$('#hashFile').files[0];if(!f)return show('hashResult','Choose a file','warn','No file selected.');try{lastHash=await hash(f);$('#copyHash').disabled=false;const test=lastHash==='275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f';show('hashResult',test?'Antivirus test fingerprint recognized':'Fingerprint created',test?'warn':'safe',lastHash+(test?' • Matches the harmless EICAR test file; remove it after testing.':' • A fingerprint alone does not prove safety.'));record('File fingerprint',test?'warn':'safe',f.name+' • '+lastHash)}catch(e){show('hashResult','Fingerprint failed','danger',e.message)}};
$('#copyHash').onclick=async()=>{await navigator.clipboard.writeText(lastHash);show('hashResult','Fingerprint copied','safe',lastHash)};
$('#phishBtn').onclick=()=>{const r=inspect($('#phishUrl').value,$('#strictMode').checked),l=level(r.score),d=r.why.join(' • ')||'No obvious URL signals.';show('phishResult','Phishing risk '+r.score+'/100',l,d);record('Phishing check',l,(r.host||'invalid')+' • '+d)};
$('#typoBtn').onclick=()=>{const h=host($('#typoDomain').value),b=h.split('.').slice(-2).join('.');let near='',dist=99;for(const x of brands){const d=lev(b,x);if(d<dist){dist=d;near=x}}const bad=b&&b!==near&&dist<=2;show('typoResult',bad?'Possible look-alike':'No close imitation found',bad?'danger':'safe',bad?b+' is '+dist+' edit(s) from '+near:'Checked against common high-value domains.');record('Look-alike check',bad?'danger':'safe',b||'invalid')};
$('#redirectBtn').onclick=()=>{const c=redirects($('#redirectUrl').value);if(!c.length)return show('redirectResult','Invalid address','danger','Enter a web address.');const r=inspect(c.at(-1),$('#strictMode').checked),l=level(r.score);show('redirectResult',c.length>1?c.length+' destinations decoded':'No encoded redirect found',l,c.join(' → ')+' • Final risk '+r.score+'/100');record('Redirect check',l,c.join(' → '))};
$('#breachBtn').onclick=()=>{const e=$('#breachEmail').value.trim();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))return show('breachResult','Enter a valid email','warn','The address is only format-checked here.');show('breachResult','Opening official checker','safe','Enter the address there; this app does not save it.');window.open('https://haveibeenpwned.com/','_blank','noopener,noreferrer')};
$('#reportBtn').onclick=()=>{const d=get();download('github-protector-security-report.json',{product:'GitHub Protector',version:'3.0.0',created:new Date().toISOString(),strictMode:!!d.strictMode,trusted:d.trusted||[],blocked:d.blocked||[],recentFindings:d.recentFindings||[],note:'Advisory browser report, not a full operating-system antivirus scan.'});show('reportResult','Report downloaded','safe','Contains settings and findings, not file contents.')};
$('#reminderBtn').onclick=async()=>{const days=Number($('#reminderDays').value),next=Date.now()+days*86400000;localStorage.setItem(REM,JSON.stringify({days,next}));if('Notification'in window&&Notification.permission==='default')await Notification.requestPermission();show('reminderResult','Reminder saved','safe','Next: '+new Date(next).toLocaleString()+'. It runs when the app opens.')};
$('#strictMode').onchange=e=>{const d=get();d.strictMode=e.target.checked;put(d);show('strictResult',e.target.checked?'Protected Browsing enabled':'Standard warnings enabled',e.target.checked?'safe':'warn',e.target.checked?'URL scoring is now stricter.':'Enable it for more cautious warnings.')};
$('#backupBtn').onclick=()=>{download('github-protector-backup.json',{format:'github-protector-backup',version:1,created:new Date().toISOString(),data:get(),reminder:localStorage.getItem(REM)});show('backupResult','Backup downloaded','safe','Keep it private because it can contain domain lists.')};
$('#restoreBtn').onclick=async()=>{const f=$('#restoreFile').files[0];if(!f)return show('backupResult','Choose a backup','warn','Select a backup JSON file.');try{const b=JSON.parse(await f.text());if(b.format!=='github-protector-backup'||b.version!==1||!b.data)throw Error('Unrecognized backup format');put(b.data);if(b.reminder)localStorage.setItem(REM,b.reminder);show('backupResult','Backup restored','safe','Reloading settings.');setTimeout(()=>location.reload(),700)}catch(e){show('backupResult','Restore failed','danger',e.message)}};
try{const r=JSON.parse(localStorage.getItem(REM));if(r&&Date.now()>=r.next){show('reminderResult','Security check due','warn','Review downloads, browser updates, and extension permissions.');if('Notification'in window&&Notification.permission==='granted')new Notification('GitHub Protector',{body:'Your scheduled security check is due.'});r.next=Date.now()+r.days*86400000;localStorage.setItem(REM,JSON.stringify(r))}}catch{}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();
;(()=>{
const KEY='githubProtectorSecurityData',$=(s,r=document)=>r.querySelector(s);
function get(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}}function put(d){localStorage.setItem(KEY,JSON.stringify(d))}
function show(id,title,level,detail){const n=$('#'+id);n.innerHTML='<span class="tool-badge '+level+'">'+level.toUpperCase()+'</span> <strong></strong><p></p>';n.querySelector('strong').textContent=title;n.querySelector('p').textContent=detail}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function mount(){if($('#securitySuite3')||!$('#securitySuite2'))return;const s=document.createElement('section');s.id='securitySuite3';s.className='card wide security-suite';
s.innerHTML='<div class="suite-head"><div><div class="eyebrow">Community-ready protection</div><h2>Security Tools Centre — Safety & Support</h2><p>Eight useful upgrades with no payments, subscriptions, advertisements, or locked features.</p></div><span class="tool-badge safe">v4.0</span></div><div class="tool-grid">'+
'<div class="tool"><h3>21. Family Device Dashboard</h3><p>Keep a local checklist for household devices. This does not spy on or remotely control them.</p><input id="deviceName" placeholder="Device name"><select id="deviceStatus"><option>Protected</option><option>Needs update</option><option>Needs review</option></select><button class="btn mini" id="addDevice">Add device</button><div id="deviceList" class="tool-result"></div></div>'+
'<div class="tool"><h3>22. Scan History & Filters</h3><p>Search recent findings by name, detail, or risk level.</p><input id="historySearch" placeholder="Search findings"><select id="historyLevel"><option value="all">All levels</option><option value="danger">Danger</option><option value="warn">Warning</option><option value="safe">Safe</option></select><button class="btn mini" id="filterHistory">Filter history</button><button class="btn alt mini" id="clearHistory">Clear history</button><div id="filteredHistory" class="tool-result"></div></div>'+
'<div class="tool"><h3>23. Website Privacy Checker</h3><p>Paste privacy-policy text for an on-device transparency review.</p><input id="privacyUrl" placeholder="Website address"><textarea id="privacyText" placeholder="Paste the website privacy policy"></textarea><button class="btn mini" id="privacyBtn">Review privacy policy</button><div id="privacyResult" class="tool-result"></div></div>'+
'<div class="tool"><h3>24. Password Strength Checker</h3><p>Runs locally and never stores or sends the password.</p><input id="passwordInput" type="password" autocomplete="new-password" placeholder="Test a password"><button class="btn mini" id="passwordBtn">Check strength</button><div id="passwordResult" class="tool-result"></div></div>'+
'<div class="tool"><h3>25. Suspicious Email Analyzer</h3><p>Paste message text only. Remove names, addresses, codes, and private information first.</p><textarea id="emailText" placeholder="Paste non-private email text"></textarea><button class="btn mini" id="emailBtn">Analyze message</button><div id="emailResult" class="tool-result"></div></div>'+
'<div class="tool"><h3>26. Browser Update Guide</h3><p>Identify the current browser family and get safe update instructions.</p><button class="btn mini" id="browserBtn">Check browser guide</button><div id="browserResult" class="tool-result"></div></div>'+
'<div class="tool"><h3>27. Security Learning Challenge</h3><p>Practice recognizing common online risks.</p><label>Which link is safer?</label><select id="quiz1"><option value="">Choose</option><option value="a">http://paypa1-login.example</option><option value="b">https://www.paypal.com/</option></select><label>A download asks you to disable antivirus. What should you do?</label><select id="quiz2"><option value="">Choose</option><option value="a">Disable it</option><option value="b">Cancel and verify the source</option></select><label>Should you reuse one password everywhere?</label><select id="quiz3"><option value="">Choose</option><option value="a">Yes</option><option value="b">No</option></select><button class="btn mini" id="quizBtn">Check answers</button><div id="quizResult" class="tool-result"></div></div>'+
'<div class="tool"><h3>28. Feedback & Bug Reporter</h3><p>Create a privacy-safe GitHub issue draft. You review it before submitting.</p><input id="feedbackTitle" placeholder="Short issue title"><textarea id="feedbackBody" placeholder="What happened? Do not include passwords, API keys, or private files."></textarea><button class="btn mini" id="feedbackBtn">Open issue draft</button><div id="feedbackResult" class="tool-result"></div></div></div>';
$('#securitySuite2').after(s);
function renderDevices(){const d=get(),a=d.familyDevices||[];$('#deviceList').innerHTML=a.length?a.map((x,i)=>'<p><strong>'+esc(x.name)+'</strong> — '+esc(x.status)+' <button class="btn alt mini removeDevice" data-i="'+i+'">Remove</button></p>').join(''):'No devices added.';document.querySelectorAll('.removeDevice').forEach(b=>b.onclick=()=>{const d=get();d.familyDevices.splice(Number(b.dataset.i),1);put(d);renderDevices()})}
function renderHistory(){const q=$('#historySearch').value.toLowerCase(),l=$('#historyLevel').value,a=(get().recentFindings||[]).filter(x=>(l==='all'||x.level===l)&&((x.name||'')+' '+(x.details||'')).toLowerCase().includes(q));$('#filteredHistory').innerHTML=a.length?a.slice(0,30).map(x=>'<p><span class="tool-badge '+esc(x.level||'safe')+'">'+esc((x.level||'safe').toUpperCase())+'</span> <strong>'+esc(x.name)+'</strong><br><small>'+esc(new Date(x.time).toLocaleString())+' — '+esc(x.details)+'</small></p>').join(''):'No matching findings.'}
$('#addDevice').onclick=()=>{const name=$('#deviceName').value.trim();if(!name)return show('deviceList','Enter a device name','warn','Examples: Family laptop or Living-room tablet.');const d=get();d.familyDevices=d.familyDevices||[];d.familyDevices.push({name,status:$('#deviceStatus').value,updated:new Date().toISOString()});put(d);$('#deviceName').value='';renderDevices()};renderDevices();
$('#filterHistory').onclick=renderHistory;$('#historySearch').oninput=renderHistory;$('#historyLevel').onchange=renderHistory;$('#clearHistory').onclick=()=>{const d=get();d.recentFindings=[];put(d);renderHistory()};renderHistory();
$('#privacyBtn').onclick=()=>{const t=$('#privacyText').value.toLowerCase();if(t.length<120)return show('privacyResult','More policy text needed','warn','Paste enough of the privacy policy to review it.');const checks=[['data collected',/collect|information we receive|personal data/],['sharing',/share|third part|service provider/],['retention',/retain|retention|delete after/],['user rights',/access|correct|delete your|opt out/],['contact',/contact|privacy@|data protection officer/],['security',/encrypt|security measure|protect your/]],missing=checks.filter(x=>!x[1].test(t)).map(x=>x[0]),score=Math.round((checks.length-missing.length)/checks.length*100);show('privacyResult','Transparency score '+score+'/100',score>=80?'safe':score>=50?'warn':'danger',missing.length?'Missing or unclear: '+missing.join(', '):'All major transparency topics were mentioned. Mentioning them does not prove good practices.')};
$('#passwordBtn').onclick=()=>{const p=$('#passwordInput').value;let score=0,why=[];if(p.length>=12)score+=2;else why.push('use at least 12 characters');if(p.length>=16)score++;if(/[a-z]/.test(p)&&/[A-Z]/.test(p))score++;else why.push('mix letter cases');if(/\d/.test(p))score++;else why.push('add numbers');if(/[^A-Za-z0-9]/.test(p))score++;else why.push('add symbols');if(/(.)\1\1|1234|password|qwerty|letmein/i.test(p)){score=Math.max(0,score-3);why.push('avoid common patterns')}const l=score>=5?'safe':score>=3?'warn':'danger';show('passwordResult',score>=5?'Strong pattern':score>=3?'Could be stronger':'Weak pattern',l,why.join(' • ')||'Use a unique password and a trusted password manager.');$('#passwordInput').value=''};
$('#emailBtn').onclick=()=>{const t=$('#emailText').value;let score=0,r=[];for(const x of [[/urgent|immediately|act now|final warning/i,20,'urgency'],[/password|verification code|one-time code|otp/i,25,'requests credentials or codes'],[/gift card|crypto|wire transfer|payment/i,30,'unusual payment request'],[/click.*link|open.*attachment|download/i,15,'asks you to open content'],[/dear customer|dear user|winner|prize/i,15,'generic or prize language'],[/disable.*security|turn off.*antivirus/i,50,'asks you to weaken security']])if(x[0].test(t)){score+=x[1];r.push(x[2])}score=Math.min(100,score);show('emailResult','Suspicion score '+score+'/100',score>=60?'danger':score>=25?'warn':'safe',r.join(' • ')||'No obvious text signals. Verify the sender through a separate trusted method.')};
$('#browserBtn').onclick=()=>{const u=navigator.userAgent;let b=/Edg\//.test(u)?'Microsoft Edge':/OPR\//.test(u)?'Opera':/Firefox\//.test(u)?'Firefox':/Chrome\//.test(u)?'Google Chrome':/Safari\//.test(u)?'Safari':'Unknown browser',guide=b==='Google Chrome'?'Menu → Help → About Google Chrome':b==='Microsoft Edge'?'Menu → Help and feedback → About Microsoft Edge':b==='Firefox'?'Menu → Help → About Firefox':b==='Safari'?'Use System Settings → General → Software Update':b==='Opera'?'Menu → Update & Recovery':'Open the browser help menu and choose About or Update';show('browserResult',b,'safe',guide+'. Restart after the update. Version detection from web pages can be limited.')};
$('#quizBtn').onclick=()=>{const answers=[$('#quiz1').value==='b',$('#quiz2').value==='b',$('#quiz3').value==='b'],score=answers.filter(Boolean).length;show('quizResult',score+'/3 correct',score===3?'safe':score>=2?'warn':'danger',score===3?'Excellent: verify domains, keep protection enabled, and use unique passwords.':'Review the questions and try again. Suspicious spelling and requests to disable protection are major warnings.')};
$('#feedbackBtn').onclick=()=>{const title=$('#feedbackTitle').value.trim(),body=$('#feedbackBody').value.trim();if(!title||!body)return show('feedbackResult','Add a title and description','warn','Do not include passwords, API keys, or private information.');const url='https://github.com/armaanshashvat2014-dot/github-protect/issues/new?title='+encodeURIComponent(title)+'&body='+encodeURIComponent(body+'\n\nApp version: 4.0.0');show('feedbackResult','Issue draft ready','safe','GitHub will open so you can review everything before submitting.');window.open(url,'_blank','noopener,noreferrer')};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();