(()=>{
const $=(s,r=document)=>r.querySelector(s);let localTranslator=null,lastPair='';
function status(title,level,detail){const n=$('#translatorStatus');n.innerHTML='<span class="tool-badge '+level+'">'+level.toUpperCase()+'</span> <strong></strong><p></p>';n.querySelector('strong').textContent=title;n.querySelector('p').textContent=detail}
async function createLocal(source,target){const pair=source+'-'+target;if(localTranslator&&lastPair===pair)return localTranslator;if(localTranslator?.destroy)localTranslator.destroy();localTranslator=null;const API=globalThis.Translator;if(API?.create){const availability=API.availability?await API.availability({sourceLanguage:source,targetLanguage:target}):'downloadable';if(availability==='unavailable')throw new Error('This language pair is unavailable in the browser.');status(availability==='available'?'On-device model ready':'Preparing translation model','warn',availability==='available'?'Translation stays on this device.':'The browser may download its language model once.');localTranslator=await API.create({sourceLanguage:source,targetLanguage:target,monitor(m){m.addEventListener('downloadprogress',e=>status('Downloading language model','warn',Math.round(e.loaded*100)+'% complete'))}});lastPair=pair;return localTranslator}if(globalThis.ai?.translator?.create){localTranslator=await globalThis.ai.translator.create({sourceLanguage:source,targetLanguage:target});lastPair=pair;return localTranslator}throw new Error('On-device translation is not supported by this browser.')}
function pair(){return $('#translatorDirection').value==='en-hi'?{source:'en',target:'hi'}:{source:'hi',target:'en'}}
async function translate(){const text=$('#translatorInput').value.trim();if(!text)return status('Enter text to translate','warn','Paste English or Hindi text first.');const {source,target}=pair(),button=$('#translateNow');button.disabled=true;button.textContent='Translating…';try{const engine=await createLocal(source,target);$('#translatorOutput').value=await engine.translate(text);status('Translation complete','safe','Translated on this device using the browser language model.')}catch{$('#externalTranslator').hidden=false;status('On-device translator unavailable','warn','No text was sent anywhere. Open the blank translator and paste it yourself.')}finally{button.disabled=false;button.textContent='Translate'}}
function open(){const modal=$('#translatorModal');modal.classList.add('open');$('#translatorInput').focus()}
function close(){const modal=$('#translatorModal');modal.classList.remove('open')}
function mount(){if($('#openTranslator'))return;const headerActions=document.querySelector('header .buttons'),notifications=$('#notificationButton'),button=document.createElement('button');button.id='openTranslator';button.type='button';button.className='btn alt mini translator-top-button';button.textContent='🌐 EN ⇄ हिं';button.title='English Hindi Translator';if(notifications)headerActions.insertBefore(button,notifications);else headerActions.append(button);const modal=document.createElement('div');modal.className='modal';modal.id='translatorModal';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','translatorTitle');modal.innerHTML='<div class="modal-box translator-box"><div class="modal-head"><div><div class="eyebrow">Private on-device translation</div><h2 id="translatorTitle">English ↔ Hindi Translator</h2></div><button class="close" id="closeTranslator" aria-label="Close">×</button></div><select id="translatorDirection"><option value="en-hi">English → Hindi</option><option value="hi-en">Hindi → English</option></select><textarea id="translatorInput" maxlength="5000" placeholder="Enter English or Hindi text"></textarea><div class="buttons"><button class="btn mini" id="translateNow">Translate</button><button class="btn alt mini" id="swapTranslation">⇄ Swap</button><button class="btn alt mini" id="copyTranslation">Copy result</button><a class="btn alt mini" id="externalTranslator" href="https://translate.google.com/" target="_blank" rel="noopener noreferrer" hidden>Open blank translator</a></div><textarea id="translatorOutput" readonly placeholder="Translation appears here"></textarea><div class="tool-result" id="translatorStatus">No translation text is uploaded by GitHub Protect.</div></div>';document.body.append(modal);button.onclick=open;$('#closeTranslator').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});$('#translateNow').onclick=translate;$('#swapTranslation').onclick=()=>{const d=$('#translatorDirection');d.value=d.value==='en-hi'?'hi-en':'en-hi';const input=$('#translatorInput'),output=$('#translatorOutput'),old=input.value;input.value=output.value;output.value=old;localTranslator?.destroy?.();localTranslator=null;lastPair='';status('Direction swapped','safe',d.options[d.selectedIndex].text)};$('#copyTranslation').onclick=async()=>{const value=$('#translatorOutput').value;if(!value)return status('Nothing to copy','warn','Translate some text first.');await navigator.clipboard.writeText(value);status('Translation copied','safe','The translated text is on your clipboard.')};if(new URLSearchParams(location.search).get('tool')==='translatorInput')open()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();